[Scheme]
Name=One Dark
ColorForeground=#ABB2BF
ColorBackground=#282C34
ColorCursor=#ABB2BF
ColorCursorForeground=#282C34
ColorCursorUseDefault=FALSE
ColorSelection=#282C34
ColorSelectionBackground=#C678DD
ColorSelectionUseDefault=FALSE
ColorBoldUseDefault=TRUE
ColorPalette=#282C34;#E06C75;#98C379;#E5C07B;#61AFEF;#C678DD;#56B6C2;#ABB2BF;#3E4452;#BE5046;#98C379;#D19A66;#61AFEF;#C678DD;#56B6C2;#5C6370
